CREATE OR REPLACE VIEW V_DISPARITATE_COST_TRAI AS
SELECT 
    s.CITY, 
    c.region AS CONTINENT,
    s.AVERAGE_MONTHLY_SALARY_AFTER_TAX_IN_2020 AS SALARIU,
    p.rent_price AS CHIRIE,
    ROUND((p.rent_price / NULLIF(s.AVERAGE_MONTHLY_SALARY_AFTER_TAX_IN_2020, 0)) * 100, 2) AS PROCENT_POVARA_CHIRIE
FROM SALARIES_DATA s
JOIN cost_living_rest_view p ON LOWER(TRIM(s.CITY)) = LOWER(TRIM(p.city))
JOIN mongodb_countries_view c ON LOWER(TRIM(s.COUNTRY)) LIKE '%' || LOWER(TRIM(c.country_name)) || '%'
WHERE s.AVERAGE_MONTHLY_SALARY_AFTER_TAX_IN_2020 > 0;
