CREATE OR REPLACE VIEW V_ECONOMIE_GLOBALE_COMPLET AS
SELECT 
    s.CITY AS ORAS, 
    s.COUNTRY AS TARA, 
    c.region AS CONTINENT,
    s.AVERAGE_MONTHLY_SALARY_AFTER_TAX_IN_2020 AS SALARIU_NET_2020,
    p.rent_price AS CHIRIE_POSTGRES,
    c.capital AS CAPITALA
FROM SALARIES_DATA s
LEFT JOIN cost_living_rest_view p ON 
    LOWER(TRIM(s.CITY)) = LOWER(TRIM(p.city))
INNER JOIN mongodb_countries_view c ON 
    LOWER(TRIM(s.COUNTRY)) LIKE '%' || LOWER(TRIM(c.country_name)) || '%'
    OR LOWER(TRIM(c.country_name)) LIKE '%' || LOWER(TRIM(s.COUNTRY)) || '%'
WHERE s.AVERAGE_MONTHLY_SALARY_AFTER_TAX_IN_2020 > 0;
