CREATE OR REPLACE VIEW V_ANALYTIC_TOP_AFFORDABILITY AS
SELECT 
    d.INCOME_SEGMENT,
    COUNT(*) AS TOTAL_ORASE,
    ROUND(AVG(f.PROCENT_CHIRIE), 2) AS PROCENT_MEDIU_CHIRIE,
    MIN(f.PROCENT_CHIRIE) AS MIN_POVARA,
    MAX(f.PROCENT_CHIRIE) AS MAX_POVARA
FROM V_FACT_RENTABILITY_INDEX f
JOIN V_DIM_INCOME_BRACKETS d ON f.CITY_KEY = d.CITY_KEY
GROUP BY d.INCOME_SEGMENT
ORDER BY PROCENT_MEDIU_CHIRIE ASC;
