CREATE OR REPLACE VIEW V_ANALYTIC_REGIONAL_HIERARCHY AS
SELECT 
    d.CONTINENT_NAME, 
    d.COUNTRY_NAME, 
    COUNT(f.CITY_KEY) AS NUMAR_ORASE,
    ROUND(AVG(f.SALARIU_NET), 2) AS MEDIE_SALARIU,
    ROUND(AVG(f.COST_CHIRIE), 2) AS MEDIE_CHIRIE
FROM V_FACT_RENTABILITY_INDEX f
JOIN V_DIM_GEOGRAPHY_HIERARCHY d ON f.CITY_KEY = d.CITY_KEY
GROUP BY ROLLUP(d.CONTINENT_NAME, d.COUNTRY_NAME);
