CREATE OR REPLACE VIEW V_AUDIT_INTEGRARE_SURSE AS
SELECT 
    c.region AS CONTINENT,
    COUNT(s.CITY) AS TOTAL_ORASE_ORACLE,
    COUNT(p.city) AS ORASE_IDENTIFICATE_POSTGRES,
    COUNT(c.country_name) AS TARI_IDENTIFICATE_MONGO
FROM SALARIES_DATA s
LEFT JOIN cost_living_rest_view p ON LOWER(TRIM(s.CITY)) = LOWER(TRIM(p.city))
LEFT JOIN mongodb_countries_view c ON LOWER(TRIM(s.COUNTRY)) LIKE '%' || LOWER(TRIM(c.country_name)) || '%'
GROUP BY c.region;
