CREATE OR REPLACE VIEW V_ANALYTIC_INCOME_VS_CAPITAL AS
SELECT 
    d1.INCOME_SEGMENT, 
    d2.CITY_CATEGORY, 
    ROUND(AVG(f.RATIO_PUTERE_CUMPARARE), 2) AS PUTERE_CUMPARARE_MEDIE
FROM V_FACT_ECONOMIC_EFFICIENCY f
JOIN V_DIM_INCOME_BRACKETS d1 ON f.CITY_KEY = d1.CITY_KEY
JOIN V_DIM_CITY_STATUS d2 ON f.CITY_KEY = d2.CITY_KEY
GROUP BY CUBE(d1.INCOME_SEGMENT, d2.CITY_CATEGORY);
