CREATE OR REPLACE VIEW V_DIM_INCOME_BRACKETS AS
SELECT 
    LOWER(TRIM(s.CITY)) AS CITY_KEY,
    s.CITY AS CITY_NAME,
    CASE 
        WHEN s.AVERAGE_MONTHLY_SALARY_AFTER_TAX_IN_2020 < 1000 THEN 'Low Income (<1000$)'
        WHEN s.AVERAGE_MONTHLY_SALARY_AFTER_TAX_IN_2020 BETWEEN 1000 AND 3000 THEN 'Medium Income (1k-3k$)'
        WHEN s.AVERAGE_MONTHLY_SALARY_AFTER_TAX_IN_2020 BETWEEN 3000 AND 5000 THEN 'High Income (3k-5k$)'
        ELSE 'Ultra-High Income (>5000$)'
    END AS INCOME_SEGMENT
FROM SALARIES_DATA s
WHERE s.AVERAGE_MONTHLY_SALARY_AFTER_TAX_IN_2020 > 0;
