# Portul standard pentru Spark SQL Service in acest proiect
server.port=10001
server.servlet.context-path=/DSA-SparkSQL-Service
server.servlet.session.persistent=false

# Logging - util pentru a vedea interogarile care vin dinspre DBeaver
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.org.apache.spark=WARN
logging.level.org.spark.service=INFO

# SpringBoot Security - Corect (dezactiveaza login-ul in browser)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.security.user.name=spark
spring.security.user.password=sql